server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.110.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.14:3306/zc_system?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: zhongchi
  clientSecret: zhongchi
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt: #本地证书和秘钥以及证书密码配置
  key-store:
    location: classpath:/zhongchi.jks
    secret: zhongchi
    alias: zhongchi
    password: zhongchi
    
    
    