server:
  port: 8081
spring:
  application:
    name: system-web
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
    
ribbon:  eureka:    enabled: true
  thymeleaf:
