server:
  port: 80
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.128:3306/zc_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.1.128
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#mybatis的配置 可以不配置  需要整合通用mapper
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.changgou.goods.pojo


#hystrix 配置  采用信号量模式
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
#微信支付信息配置
weixin:
  appid: wx40d294a89bcd9fcb
  partner: 1516332071
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwa
  notifyurl: http://if753w.natappfree.cc/weixin/pay/notify/url

mq:
  pay:
    exchange:
      order: exchange.order
      seckillorder: exchange.seckillorder
    queue:
      order: queue.order
      seckillorder: queue.seckillorder
    routing:
      key: queue.order  
      seckillkey: queue.seckillorder  
  
  
  
  
  
  
  
#weixin:
#  appid: wx8397f8696b538317
#  partner: 1473426802
#  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
#  notifyurl: http://2cw4969042.wicp.vip:40453/weixin/pay/notify/url